// File generated by flutterfire configure - run again if project settings change
// TODO: replace with real Firebase project IDs before release.

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static Map<String, dynamic> get currentPlatform {
    // This is a dummy implementation
    // In real implementation, this would return FirebaseOptions based on platform
    return web;
  }

  static const Map<String, dynamic> web = {
    'apiKey': 'AIzaSyDummy-Web-ApiKey-Example123456789',
    'appId': '1:123456789012:web:abcdef1234567890abcdef',
    'messagingSenderId': '123456789012',
    'projectId': 'globgram-p2p-dummy',
    'authDomain': 'globgram-p2p-dummy.firebaseapp.com',
    'storageBucket': 'globgram-p2p-dummy.appspot.com',
    'measurementId': 'G-DUMMY123456',
  };

  static const Map<String, dynamic> android = {
    'apiKey': 'AIzaSyDummy-Android-ApiKey-Example123456789',
    'appId': '1:123456789012:android:abcdef1234567890abcdef',
    'messagingSenderId': '123456789012',
    'projectId': 'globgram-p2p-dummy',
    'storageBucket': 'globgram-p2p-dummy.appspot.com',
  };

  static const Map<String, dynamic> ios = {
    'apiKey': 'AIzaSyDummy-iOS-ApiKey-Example123456789',
    'appId': '1:123456789012:ios:abcdef1234567890abcdef',
    'messagingSenderId': '123456789012',
    'projectId': 'globgram-p2p-dummy',
    'storageBucket': 'globgram-p2p-dummy.appspot.com',
    'iosBundleId': 'com.example.globgramP2p',
  };

  static const Map<String, dynamic> macos = {
    'apiKey': 'AIzaSyDummy-macOS-ApiKey-Example123456789',
    'appId': '1:123456789012:macos:abcdef1234567890abcdef',
    'messagingSenderId': '123456789012',
    'projectId': 'globgram-p2p-dummy',
    'storageBucket': 'globgram-p2p-dummy.appspot.com',
    'iosBundleId': 'com.example.globgramP2p',
  };

  static const Map<String, dynamic> windows = {
    'apiKey': 'AIzaSyDummy-Windows-ApiKey-Example123456789',
    'appId': '1:123456789012:web:abcdef1234567890abcdef',
    'messagingSenderId': '123456789012',
    'projectId': 'globgram-p2p-dummy',
    'authDomain': 'globgram-p2p-dummy.firebaseapp.com',
    'storageBucket': 'globgram-p2p-dummy.appspot.com',
    'measurementId': 'G-DUMMY123456',
  };
}
