// File generated by FlutterFire CLI
// TODO: Replace with real Firebase project configuration before production deployment
// Run 'flutterfire configure' to generate proper configuration
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with actual Firebase Web configuration
  // Get these values from Firebase Console > Project Settings > General > Your apps > Web app
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'TODO-replace-with-actual-web-api-key',
    appId: 'TODO-replace-with-actual-web-app-id',
    messagingSenderId: 'TODO-replace-with-actual-sender-id',
    projectId: 'globgram-p2p-project', // TODO: Replace with actual project ID
    authDomain:
        'globgram-p2p-project.firebaseapp.com', // TODO: Replace with actual domain
    storageBucket:
        'globgram-p2p-project.appspot.com', // TODO: Replace with actual bucket
    measurementId:
        'TODO-replace-with-actual-measurement-id', // Optional for Analytics
  );

  // TODO: Replace with actual Firebase Android configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'TODO-replace-with-actual-android-api-key',
    appId: 'TODO-replace-with-actual-android-app-id',
    messagingSenderId: 'TODO-replace-with-actual-sender-id',
    projectId: 'globgram-p2p-project', // TODO: Replace with actual project ID
    storageBucket:
        'globgram-p2p-project.appspot.com', // TODO: Replace with actual bucket
  );

  // TODO: Replace with actual Firebase iOS configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TODO-replace-with-actual-ios-api-key',
    appId: 'TODO-replace-with-actual-ios-app-id',
    messagingSenderId: 'TODO-replace-with-actual-sender-id',
    projectId: 'globgram-p2p-project', // TODO: Replace with actual project ID
    storageBucket:
        'globgram-p2p-project.appspot.com', // TODO: Replace with actual bucket
    iosBundleId:
        'com.example.globgramP2p', // TODO: Replace with actual bundle ID
  );

  // TODO: Replace with actual Firebase macOS configuration
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'TODO-replace-with-actual-macos-api-key',
    appId: 'TODO-replace-with-actual-macos-app-id',
    messagingSenderId: 'TODO-replace-with-actual-sender-id',
    projectId: 'globgram-p2p-project', // TODO: Replace with actual project ID
    storageBucket:
        'globgram-p2p-project.appspot.com', // TODO: Replace with actual bucket
    iosBundleId:
        'com.example.globgramP2p', // TODO: Replace with actual bundle ID
  );

  // TODO: Replace with actual Firebase Windows configuration
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'TODO-replace-with-actual-windows-api-key',
    appId: 'TODO-replace-with-actual-windows-app-id',
    messagingSenderId: 'TODO-replace-with-actual-sender-id',
    projectId: 'globgram-p2p-project', // TODO: Replace with actual project ID
    authDomain:
        'globgram-p2p-project.firebaseapp.com', // TODO: Replace with actual domain
    storageBucket:
        'globgram-p2p-project.appspot.com', // TODO: Replace with actual bucket
    measurementId:
        'TODO-replace-with-actual-measurement-id', // Optional for Analytics
  );
}
