// File generated by FlutterFire CLI
// Replace with real Firebase project configuration before production deployment
// Run 'flutterfire configure' to generate proper configuration
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web configuration - Replace with actual Firebase Web configuration

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Sug8gr_feCs7XirAzzEiqFMK2ZHzDks',
    appId: '1:786174087282:web:6322c68e14b9c81f44f2eb',
    messagingSenderId: '786174087282',
    projectId: 'globgram02',
    authDomain: 'globgram02.firebaseapp.com',
    storageBucket: 'globgram02.firebasestorage.app',
  );

  // Get these values from Firebase Console > Project Settings > General > Your apps > Web app

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtAUknIOZ92eKNPo9FhwIdNR2RSawxGnY',
    appId: '1:786174087282:android:81cb03d084ac0b7944f2eb',
    messagingSenderId: '786174087282',
    projectId: 'globgram02',
    storageBucket: 'globgram02.firebasestorage.app',
  );

  // Android configuration - Replace with actual Firebase Android configuration  

  // iOS configuration - Replace with actual Firebase iOS configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyEFwXxN6k9vF2mL3jH8uQ4pR7sT5wE9oL1',
    appId: '1:123456789012:ios:a1b2c3d4e5f6g7h8',
    messagingSenderId: '123456789012',
    projectId: 'globgram-p2p-project',
    storageBucket: 'globgram-p2p-project.appspot.com',
    iosBundleId: 'com.example.globgramP2p',
  );

  // macOS configuration - Replace with actual Firebase macOS configuration
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyGHwXxN7k1vF3mM4jH9uQ5pR8sT6wE1oL7',
    appId: '1:123456789012:ios:a1b2c3d4e5f6g7h8',
    messagingSenderId: '123456789012',
    projectId: 'globgram-p2p-project',
    storageBucket: 'globgram-p2p-project.appspot.com',
    iosBundleId: 'com.example.globgramP2p',
  );

  // Windows configuration - Replace with actual Firebase Windows configuration
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyIJwXxN8k2vF4mN5jH1uQ6pR9sT7wE2oL8',
    appId: '1:123456789012:web:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '123456789012',
    projectId: 'globgram-p2p-project',
    authDomain: 'globgram-p2p-project.firebaseapp.com',
    storageBucket: 'globgram-p2p-project.appspot.com',
    measurementId: 'G-XYZ789ABC123', // Optional for Analytics
  );
}